apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
  namespace: myflix
  labels:
    app: interaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
        - name: interaction-service
          image: 025211337216.dkr.ecr.ap-south-1.amazonaws.com/myflix/interaction-service:latest
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: myflix-common-config
            - secretRef:
                name: myflix-database-secret
            - secretRef:
                name: myflix-jwt-secret
          env:
            - name: PORT
              value: "8089"
---
apiVersion: v1
kind: Service
metadata:
  name: interaction-service
  namespace: myflix
spec:
  selector:
    app: interaction-service
  ports:
    - port: 8089
      targetPort: 8089