apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: myflix
type: Opaque

stringData:
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: admin@123
  JWT_SECRET: ER6b{mAk5zw.(dCt#>X=T}hs>324B(7-/dT+qjt>{:z
  TMDB_API_KEY: ebe7d8b6bb429b017bf62e41a4f42820
  RAZORPAY_KEY_ID: your-razorpay-key-id
  RAZORPAY_KEY_SECRET: your-razorpay-key-secret
