apiVersion: v1
kind: Secret
metadata:
  name: myflix-database-secret
  namespace: myflix
type: Opaque

stringData:
  DATABASE_URL: postgres://myflix_admin:admin123@myflix-postgres-postgresql:5432/myflix?sslmode=disable
