apiVersion: v1
kind: Service

metadata:
  name: media-library-service
  namespace: myflix

spec:
  selector:
    app: media-library-service

  ports:
    - port: 8001
      targetPort: 8001

  type: ClusterIP
