global:
  scrape_interval: 15s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets:
          - api-gateway:8094

  - job_name: auth-service
    static_configs:
      - targets:
          - auth-service:8083

  - job_name: user-service
    static_configs:
      - targets:
          - user-service:8085

  - job_name: analytics-service
    static_configs:
      - targets:
          - analytics-service:8086

  - job_name: recommendation-service
    static_configs:
      - targets:
          - recommendation-service:8087

  - job_name: metadata-service
    static_configs:
      - targets:
          - metadata-service:8088

  - job_name: interaction-service
    static_configs:
      - targets:
          - interaction-service:8089

  - job_name: watchhistory-service
    static_configs:
      - targets:
          - watchhistory-service:8090

  - job_name: payment-service
    static_configs:
      - targets:
          - payment-service:8091

  - job_name: transcoding-service
    static_configs:
      - targets:
          - transcoding-service:8092

  - job_name: subscription-service
    static_configs:
      - targets:
          - subscription-service:8093

  - job_name: media-library-service
    static_configs:
      - targets:
          - media-library-service:8001

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
