apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myflix-database-secret
  namespace: myflix
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: myflix-database-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: myflix/database-url_1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myflix-jwt-secret
  namespace: myflix
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: myflix-jwt-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: myflix/jwt-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myflix-razorpay-secret
  namespace: myflix
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: myflix-razorpay-secret
    creationPolicy: Owner
  data:
    - secretKey: RAZORPAY_KEY_ID
      remoteRef:
        key: myflix/razorpay
        property: RAZORPAY_KEY_ID
    - secretKey: RAZORPAY_KEY_SECRET
      remoteRef:
        key: myflix/razorpay
        property: RAZORPAY_KEY_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myflix-tmdb-secret
  namespace: myflix
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: myflix-tmdb-secret
    creationPolicy: Owner
  data:
    - secretKey: TMDB_API_KEY
      remoteRef:
        key: myflix/tmdb-api-key
