pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    script {
                        def scannerHome = tool(
                            name: 'SonarQubeScanner',
                            type: 'hudson.plugins.sonar.SonarRunnerInstallation'
                        )

                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=myflix-auth-service \
                            -Dsonar.projectName=myflix-auth-service \
                            -Dsonar.sources=.
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage("Docker Build"){
            script {
                def image = docker.build(
                    "myflix-auth-service:${BUILD_NUMBER}",
                    "."
                )
            }
        }
    }
}